name: backend-cd

on:
  workflow_run:
    workflows: ["backend-ci"]
    types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Get Old Image ID
      run: |
        Old_IMAGE_ID=$(sudo docker images --filter=reference=nakki0404/riceark:latest --format "{{.ID}}")
    - name: Pull Docker image
      run: sudo docker pull nakki0404/riceark:latest  
    # - name: Server Down
    #   run : sudo docker-compose down
    - name: Delete Old Image ID
      run: sudo docker rmi $Old_IMAGE_ID
    # - name: Server On
    #   run : sudo docker-compose up -d
    
