name: backend-cd

on:
  workflow_run:
    workflows: ["backend-ci"]
    types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nakki0404/riceark:latest  
    - name: Server Reboot
      run: sudo docker-compose up -d
    - name: Delete Old Docker Image
      run: sudo docker rmi nakki0404/riceark
    
